### ISSUE TITLE
Must have list for v1.0.0

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanpcmcquen/unclosedTagFinder#2]
### TODO:

**Important**:

- [x] Read file input.
- [x] Accomodate tag names with attributes.
- [x] Ignore self closing tags.
- [x] Read remote files.
- [x] Accomodate user input.
- [x] Improve command line interface and output.
- [x] Give line numbers of unclosed tags.

**Comment by ryanpcmcquen** [comment]
Moving other requests to a separate issue since we are going to release 1.0.0.
